# fly.toml app configuration file generated for fiserv-inventory on 2025-02-08T22:04:10-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fiserv-web-app"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 550
    soft_limit = 500

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "10s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
