[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://fiserv-inventory-api.fly.dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
