import { EquipmentInstallation } from '../types/project';

const mockEquipment: EquipmentInstallation[] = [
  {
    installation_id: 1,
    project_id: 1,
    equipment_name: "Commercial 6-Burner Gas Range",
    equipment_type: "Cooking Equipment",
    manufacturer: "Vulcan",
    model: "V6B36",
    serial_number: "VN2023451",
    planned_installation_date: "2025-03-15",
    actual_installation_date: "2025-03-18",
    status: "installed",
    location_in_facility: "Main Kitchen - Cooking Line",
    installation_notes: "Installation completed with minor delay due to gas line modifications",
    dependencies: null,
    created_at: "2025-02-20T10:15:00Z",
    updated_at: "2025-03-18T16:30:00Z"
  },
  {
    installation_id: 2,
    project_id: 1,
    equipment_name: "Walk-in Cooler",
    equipment_type: "Refrigeration",
    manufacturer: "Amerikooler",
    model: "QC081272",
    serial_number: "AM20250089",
    planned_installation_date: "2025-03-25",
    actual_installation_date: null,
    status: "ordered",
    location_in_facility: "Rear Kitchen Area",
    installation_notes: "8' x 12' x 7'2\" indoor cooler with top-mounted refrigeration unit",
    dependencies: null,
    created_at: "2025-02-25T11:30:00Z",
    updated_at: "2025-03-10T09:45:00Z"
  },
  {
    installation_id: 3,
    project_id: 1,
    equipment_name: "Conveyor Pizza Oven",
    equipment_type: "Cooking Equipment",
    manufacturer: "Lincoln",
    model: "3240-000-R",
    serial_number: "LP10289345",
    planned_installation_date: "2025-04-05",
    actual_installation_date: null,
    status: "ordered",
    location_in_facility: "Pizza Station",
    installation_notes: "Requires dedicated 208V electrical circuit and ventilation hood",
    dependencies: null,
    created_at: "2025-03-01T14:20:00Z",
    updated_at: "2025-03-12T10:15:00Z"
  },
  {
    installation_id: 4,
    project_id: 1,
    equipment_name: "Commercial Dishwasher",
    equipment_type: "Cleaning Equipment",
    manufacturer: "Hobart",
    model: "AM15T-BAS",
    serial_number: "HB2025673",
    planned_installation_date: "2025-04-10",
    actual_installation_date: null,
    status: "ordered",
    location_in_facility: "Dish Room",
    installation_notes: "High-temperature sanitizing model with built-in booster heater",
    dependencies: null,
    created_at: "2025-03-05T09:45:00Z",
    updated_at: "2025-03-15T11:20:00Z"
  },
  {
    installation_id: 5,
    project_id: 2,
    equipment_name: "Double Stack Combi Oven",
    equipment_type: "Cooking Equipment",
    manufacturer: "Rational",
    model: "iCombi Pro 20-2/1",
    serial_number: "RCB2025129",
    planned_installation_date: "2025-04-15",
    actual_installation_date: null,
    status: "pending",
    location_in_facility: "Banquet Kitchen",
    installation_notes: "Requires water filtration system and drain installation",
    dependencies: null,
    created_at: "2025-03-10T10:30:00Z",
    updated_at: "2025-03-10T10:30:00Z"
  },
  {
    installation_id: 6,
    project_id: 2,
    equipment_name: "Walk-in Freezer",
    equipment_type: "Refrigeration",
    manufacturer: "Amerikooler",
    model: "QF101410",
    serial_number: "AM20250103",
    planned_installation_date: "2025-04-20",
    actual_installation_date: null,
    status: "pending",
    location_in_facility: "Banquet Kitchen Storage Area",
    installation_notes: "10' x 14' x 7'6\" freezer with remote condensing unit",
    dependencies: null,
    created_at: "2025-03-12T14:15:00Z",
    updated_at: "2025-03-12T14:15:00Z"
  },
  {
    installation_id: 7,
    project_id: 3,
    equipment_name: "Serving Line",
    equipment_type: "Food Service Equipment",
    manufacturer: "Duke Manufacturing",
    model: "TEHF-88",
    serial_number: "DM2025087",
    planned_installation_date: "2025-06-25",
    actual_installation_date: null,
    status: "pending",
    location_in_facility: "Cafeteria Service Area",
    installation_notes: "Hot food serving counter with 8 wells, sneeze guard, and heat lamps",
    dependencies: null,
    created_at: "2025-03-15T15:45:00Z",
    updated_at: "2025-03-15T15:45:00Z"
  },
  {
    installation_id: 8,
    project_id: 4,
    equipment_name: "Tilting Kettle",
    equipment_type: "Cooking Equipment",
    manufacturer: "Cleveland",
    model: "KGL-40T",
    serial_number: "CL2025342",
    planned_installation_date: "2025-05-20",
    actual_installation_date: null,
    status: "pending",
    location_in_facility: "Hospital Kitchen - Cooking Area",
    installation_notes: "40-gallon gas tilting kettle with electronic spark ignition",
    dependencies: null,
    created_at: "2025-03-20T11:30:00Z",
    updated_at: "2025-03-20T11:30:00Z"
  }
];

export default mockEquipment; 